services:
  - type: web
    name: smart-tools-bot
    env: python
    plan: free # Start with free, upgrade only for the rebuild
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - fromSecretFile:
          name: .env
          path: .env
    disk:
      name: bot-data-disk
      mountPath: /var/data
      sizeGB: 1
