services:
  - name: smart-tools-bot
    type: web
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    healthCheckPath: /
    disks:
      - name: bot-data-disk
        mountPath: /var/data
        sizeGB: 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - fromSecretFile:
          name: .env
          path: .env

  - name: build-index-worker
    type: worker
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python create_embeddings.py"
    disks:
      - name: bot-data-disk
        mountPath: /var/data
        sizeGB: 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - fromSecretFile:
          name: .env
          path: .env
